# mux
#alias temp="source ~/dotfiles/lib/temp.sh"
alias dot="mux dot"
alias temp="mux temp"
alias desk="mux desk"
alias start="mux start"
alias script="mux script"
alias repo="mux repo"
alias gitbook="mux gitbook"
alias play="mux play"