source $nex_mux_path/lib/mux_cd.sh
alias home="nx_mux_cd home $HOME"
alias repo="nx_mux_cd repo $HOME/repos"
alias temp="nx_mux_cd temp $HOME/temp"
alias space="nx_mux_cd temp $HOME/space"
alias play="nx_mux_cd play $HOME/playDoh"
alias any="nx_mux_cd any $HOME/anything"
alias desk="nx_mux_cd desktop $HOME/desktop"
alias dot="nx_mux_cd dot $HOME/dotfiles"
alias book="nx_mux_cd gitbook $HOME/gitbooks"
alias store="nx_mux_cd storage $HOME/storage_tmp"
