# places
alias current="nx_mux_cd current ~/current"
alias temp="nx_mux_cd temp ~/temp"
alias space="nx_mux_cd space ~/space"
alias home="nx_mux_cd home ~/home"
alias con="nx_mux_cd conn ~/conn"
alias proc="nx_mux_cd proc ~/proc"
alias repo="nx_mux_cd repo ~/repos"
alias dot="nx_mux_cd dot ~/dotfiles"
alias ephem="nx_mux_cd ephem ~/ephemar"
